repo:
- '*'

frontend:
- any: ['services/web/app/**/*.js', 'services/web/app/**/*.html']

backend:
- any: ['services/web/app/**/*.py']

database:
- any: ['services/web/app/**/models.py', 'services/web/app/**/models/*.py']
