version: '3.2'

services:
  web:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
    - ./:/limbus
    environment:
      - FLASK_CONFIG=dev
      - FLASK_APP=/limbus/limbus/app
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    expose:
      - 5000
    ports:
      - 5000:5000

  db:
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: