version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./services/htpasswd:/etc/nginx/htpasswd
      - ./services/nginx/html:/usr/share/nginx/html

    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - nginx
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-ssl
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/certs:/etc/nginx/certs
      - ./services/htpasswd:/etc/nginx/htpasswd
      - ./services/nginx/html:/usr/share/nginx/html
    links:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    networks:
      - nginx
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/:/limbus/
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      .env
    
    command: venv/bin/gunicorn --bind 0.0.0.0:5000 run:app
  db:
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  nginx:
    external: true

volumes:
  postgres_data: