version: "3.3"
services:
  web:
    build: .
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432