version: "3"

services:
  web:
    name: limbus-web
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web/:/limbus/
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on: 
      - db
    env_file: .env
    command: venv/bin/gunicorn --bind 0.0.0.0:5000 run:app
  db:
    name: limbus-db
    image: postgres:10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx-proxy:
    name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
  letsencrypt:
    name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhostd:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy

volumes:
  postgres_data:
  certs:
  html:
  vhostd: