version: "3.3"


services:
  web:
    build: .
    volumes:
    - ./:/limbus
    - virtualenv:/opt/venv
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      - postgres      

  postgres:
    image: postgres:10
    env_file: .env
    expose:
      - 5432

volumes:
  virtualenv:
