from ..FormEnum import FormEnum


class UnitsOfMeasurement(FormEnum):
    # This is currently pulled from UO.
    ACU = "Acceleration Unit"
    ANU = "Angle Unit"
    AAU = "Angle Acceleration Unit"
    AVU = "Angle Acceleration Unit"
    ARU = "Area Unit"
    BAU = "Base Unit"
    CAU = "Catalytic Activity Unit"
    COU = "Concentration Unit"
    CNU = "Conduction Unit"
    DEU = "Density Unit"
    DIU = "Dimensionless Unit"
    ELC = "Electric Charge"
    ECU = "Electric Current Unit"
    EFU = "Electric Field Strength Unit"
    EPD = "Electric Potential Difference Unit"
    EUN = "Energy Unit"
    FOU = "Force Unit"
    FRU = "Frequency Unit"
    INU = "Information Unit"
    LEU = "Length Unit"
    LIU = "Light Unit"
    MFD = "Magnetic Flux Density Unit"
    MFU = "Magnetic Flux Unit"
    MAU = "Mass Unit"
    MOU = "Momentum Unit"
    POU = "Power Unit"
    PRU = "Pressure Unit"
    RAU = "Radiation Unit"
    RAT = "Rate Unit"
    SPU = "Speed/Velocity Unit"
    SUU = "Substance Unit"
    STU = "Surface Tension Unit"
    TEU = "Temperature Unit"
    TIU = "Time Unit"
    TUU = "Turbidity Unit"
    VIU = "Viscosity Unit"
    VOU = "Volume Unit"
    VFR = "Volumetric Flow Rate Unit"
