name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Download DOID
        run: wget https://users.aber.ac.uk/keo7/doid.xrdf ; mv doid.xrdf /limbus/ontologies/
      - name: Move .env
        run: cp .env.example .env
      - name: Build the stack
        run: |
          docker-compose build
      - run: echo "🍏 This job's status is ${{ job.status }}."


