name: Docker Image CI (testing)

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get scripts in PATH and download testing environment file.
      run: source docker_helpers.sh && wget http://users.aber.ac.uk/keo7/.env && limbus-bwd && limbus-test
