name: Docker Image CI (testing)

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check where we are.
      run: ls /
    - name: Again...
      run: pwd
    - name: Build the stack.
      run: docker-compose build
    - name: Install wheel.
      run: docker-compose run web sh -c "python3 -m venv venv && venv/bin/pip install wheel"
    - name: Install all other deps.
      run: docker-compose run web sh -c "python3 -m venv venv && venv/bin/pip install -r requirements.txt && yarn install"
    - name: Test to see if built
      run: docker-compose run --service-ports web sh -c "venv/bin/python limbus/run.py"
